### ISSUE TITLE
Getting 403 Client Error with "healthy" token

### ISSUE THREAD

**Issue by dmytro-k-zemingo** [campos-pay/sonarqube-pr-comment#12]
Good afternoon!
I have Sonar token (User-type) that works for getting `project_status` from Sonar API:
![Screenshot 2024-10-31 at 14 53 54](https://github.com/user-attachments/assets/62a5e9ef-1b4e-48c3-bd38-34e68a16d8b9)
..but from `sonarqube-pr-comment` extension I'm getting 403:
![Screenshot 2024-10-31 at 14 57 35](https://github.com/user-attachments/assets/d3f1a307-ea33-4260-b91d-63495b0486b9)
Scanning with this token works well too
Could you please advice what could be a reson?
Thanks!

**Comment by Guerlielton** [comment]
Hello @dmytro-k-zemingo thanks for open this issue.

I've tested it to find some issue, but it's all ok
I appreciate if can you provide more detail about your config, below share my example. 
![image](https://github.com/user-attachments/assets/c5c43b4e-7a12-492e-9e75-8f627c1cc1cf)
## configuration example
![image](https://github.com/user-attachments/assets/75ccd624-d174-4d63-b6f6-49e94f555beb)

**Comment by dmytro-k-zemingo** [comment]
thanks for the check, I've installed new Sonar instance and it works fine, so I think it's an issue with other Sonar instance, not  `sonarqube-pr-comment` task..

**Comment by Guerlielton** [comment]
@dmytro-k-zemingo Thanks so much if you have any questions let me know.
