### ISSUE TITLE
Fetches the Report from master branch(default) only from Sonarqube  not for pull requests?

### ISSUE THREAD

**Issue by prashaarora** [campos-pay/sonarqube-pr-comment#6]
I think your script does not fetches the Sonar info for pull request , I am getting report analysis back in github as comment for whatever I have in master branch (default)instead of PR(for feature branch)

**Comment by Guerlielton** [comment]
Hello @prashaarora sorry for to delay, do you use the Sonarqube free version?  if yes the Sonarqube free have only branch main.
